#! /usr/bin/env python

"""List fields in an OpenERP model.
"""

import sys
import argparse
import csv
from oekit import oe_client_env
from itertools import starmap

def main(options):
    """Main program."""
    cl = oe_client_env.OEClientEnv()
    oe = cl.get_proxy()
    fields = oe.execute(options.model_name, 'fields_get')
    if options.names_only:
        sys.stdout.writelines(('%s\n' % field) for field in sorted(fields))
    else:
        outcsv = csv.writer(sys.stdout)
        outcsv.writerow(['field_name', 'type', 'relation', 'string'])
        outcsv.writerows(field_rows(fields))
    return

def field_rows(fields):
    """Format rows"""
    return starmap(format_field_row, sorted(fields.items(), key=first))

def format_field_row(name, field_dict):
    return [name, field_dict['type'], field_dict.get('relation', ''), field_dict['string']]

# for sorting
def first(a_tuple):
    """Get first item from an indexable sequence, e.g. a tuple"""
    return a_tuple[0]

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
               description="get fields in an OpenERP model as CSV report",
             )
    # parser.add_argument() calls here
    parser.add_argument('model_name', help='name of model')
    parser.add_argument('-n', '--names-only', action='store_true',
        help='only list field names, with no header'
    )
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())

__COPYRIGHT__ = """The MIT License (MIT)

Copyright (c) 2013 Nicholas Booker <NMBooker@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

