#! /usr/bin/env python

"""List fields in an OpenERP model.
"""

import sys
import argparse
import csv
from oekit import oe_client_env
from itertools import starmap

def main(options):
    """Main program."""
    cl = oe_client_env.OEClientEnv()
    oe = cl.get_proxy()
    fields = oe.execute(options.model_name, 'fields_get')
    if options.names_only:
        sys.stdout.writelines(('%s\n' % field) for field in sorted(fields))
    else:
        outcsv = csv.writer(sys.stdout)
        outcsv.writerow(['field_name', 'type', 'relation', 'string', 'required'])
        outcsv.writerows(field_rows(fields))
    return

def field_rows(fields):
    """Format rows"""
    return starmap(format_field_row, sorted(fields.items(), key=first))

def format_field_row(name, field_dict):
    return [name, field_dict['type'], field_dict.get('relation', ''), field_dict['string'], field_dict['required']]

# for sorting
def first(a_tuple):
    """Get first item from an indexable sequence, e.g. a tuple"""
    return a_tuple[0]

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
               description="get fields in an OpenERP model as CSV report",
             )
    # parser.add_argument() calls here
    parser.add_argument('model_name', help='name of model')
    parser.add_argument('-n', '--names-only', action='store_true',
        help='only list field names, with no header'
    )
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())


__COPYRIGHT__ = """

This program is part of oekit: https://github.com/nmbooker/oekit

Copyright (c) 2015 Nicholas Booker <NMBooker@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""
