#! /usr/bin/env python

"""List fields in an OpenERP model.
"""

import sys
import csv
from itertools import starmap
from oekit.clientfactory import OEProxyClientFactory
from oekit.script import OdooScript

class OEDescribe(OdooScript):
    def description(self):
        return "get fields in an OpenERP model as CSV report"

    def add_extra_arguments(self, parser):
        parser.add_argument('model_name', help='name of model')
        parser.add_argument('-n', '--names-only', action='store_true',
            help='only list field names, with no header'
        )

    def get_client_factory(self):
        return OEProxyClientFactory()

    def _main(self):
        oe = self.oe
        options = self.options
        fields = oe.execute(options.model_name, 'fields_get')
        if options.names_only:
            sys.stdout.writelines(('%s\n' % field) for field in sorted(fields))
        else:
            outcsv = csv.writer(sys.stdout)
            outcsv.writerow(['field_name', 'type', 'relation', 'string', 'required'])
            outcsv.writerows(field_rows(fields))
        
def field_rows(fields):
    """Format rows"""
    return starmap(format_field_row, sorted(fields.items(), key=first))

def format_field_row(name, field_dict):
    return [name, field_dict['type'], field_dict.get('relation', ''), field_dict['string'], field_dict.get('required')]

# for sorting
def first(a_tuple):
    """Get first item from an indexable sequence, e.g. a tuple"""
    return a_tuple[0]

if __name__ == "__main__":
    OEDescribe().main()



__COPYRIGHT__ = """

This program is part of oekit: https://github.com/nmbooker/oekit

Copyright (c) 2016 Nicholas Booker <NMBooker@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""
