#! /usr/bin/env python

"""Dump records from an OpenERP model into CSV.
"""

import sys
import argparse

from oekit import oe_client_env, csvdump

def main(options):
    """Main program."""
    oe = oe_client_env.OEClientEnv().get_proxy()
    extra_kwargs = {}
    if options.ids_stdin:
        extra_kwargs['ids'] = [int(line.strip()) for line in sys.stdin]
    csvdump.dump_csv(oe, options.model_name, options.fields, outfile=sys.stdout, **extra_kwargs)
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
               description="Dump the contents of an OpenERP model to CSV",
             )
    # parser.add_argument() calls here
    parser.add_argument('model_name', help='name of model e.g. res.partner')
    parser.add_argument('fields', nargs='+', help='fields you want')
    parser.add_argument('--ids-stdin', '-i', action='store_true', help='get only the ids from stdin')
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())

__COPYRIGHT__ = """The MIT License (MIT)

Copyright (c) 2013 Nicholas Booker <NMBooker@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""
